site_name: My Docs
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
site_url: https://pedrubik2000.github.io/