site_name: La guía de Pedro
site_url: https://pedrubik2000.github.io/
site_description: La guía de Yomitan, Anki y Japonés
site_author: Pedro
nav:
  - Bienvenido:
    - Introducción: 'guia-del-japones/index.md'
    - Changelog (2024-02-26): 'guia-del-japones/anki.md'
    - About: 'guia-del-japones/about.md'
    - Credits: 'guia-del-japones/credits.md'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: deep purple
      accent: deep purple
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  homepage: https://pedrubik2000.github.io/la-guia-floja-del-japo/
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Pedrubik2000
      name: Github - Pedro
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4eU2zQzV
      name: Discord - Aprender Japonés Rápido
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@PedroEchevarria2000
      name: Youtube - Pedro      
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
    provider: google
    property: G-70F7EXNRSJ
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - git-revision-date-localized
  - search:
      lang:
        - es
        - ja
  